// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xwritebinary.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XWritebinary_CfgInitialize(XWritebinary *InstancePtr, XWritebinary_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->S_axi_bundle_BaseAddress = ConfigPtr->S_axi_bundle_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XWritebinary_Start(XWritebinary *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_AP_CTRL) & 0x80;
    XWritebinary_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_AP_CTRL, Data | 0x01);
}

u32 XWritebinary_IsDone(XWritebinary *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XWritebinary_IsIdle(XWritebinary *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XWritebinary_IsReady(XWritebinary *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XWritebinary_EnableAutoRestart(XWritebinary *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XWritebinary_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_AP_CTRL, 0x80);
}

void XWritebinary_DisableAutoRestart(XWritebinary *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XWritebinary_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_AP_CTRL, 0);
}

void XWritebinary_Set_code(XWritebinary *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XWritebinary_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_CODE_DATA, Data);
}

u32 XWritebinary_Get_code(XWritebinary *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_CODE_DATA);
    return Data;
}

void XWritebinary_Set_leftover_i(XWritebinary *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XWritebinary_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_LEFTOVER_I_DATA, Data);
}

u32 XWritebinary_Get_leftover_i(XWritebinary *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_LEFTOVER_I_DATA);
    return Data;
}

u32 XWritebinary_Get_leftover_o(XWritebinary *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_LEFTOVER_O_DATA);
    return Data;
}

u32 XWritebinary_Get_leftover_o_vld(XWritebinary *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_LEFTOVER_O_CTRL);
    return Data & 0x1;
}

void XWritebinary_Set_leftoverBits_i(XWritebinary *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XWritebinary_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_LEFTOVERBITS_I_DATA, Data);
}

u32 XWritebinary_Get_leftoverBits_i(XWritebinary *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_LEFTOVERBITS_I_DATA);
    return Data;
}

u32 XWritebinary_Get_leftoverBits_o(XWritebinary *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_LEFTOVERBITS_O_DATA);
    return Data;
}

u32 XWritebinary_Get_leftoverBits_o_vld(XWritebinary *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_LEFTOVERBITS_O_CTRL);
    return Data & 0x1;
}

void XWritebinary_Set_count_i(XWritebinary *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XWritebinary_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_COUNT_I_DATA, Data);
}

u32 XWritebinary_Get_count_i(XWritebinary *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_COUNT_I_DATA);
    return Data;
}

u32 XWritebinary_Get_count_o(XWritebinary *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_COUNT_O_DATA);
    return Data;
}

u32 XWritebinary_Get_count_o_vld(XWritebinary *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_COUNT_O_CTRL);
    return Data & 0x1;
}

u32 XWritebinary_Get_output_r_BaseAddress(XWritebinary *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_BASE);
}

u32 XWritebinary_Get_output_r_HighAddress(XWritebinary *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_HIGH);
}

u32 XWritebinary_Get_output_r_TotalBytes(XWritebinary *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_HIGH - XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_BASE + 1);
}

u32 XWritebinary_Get_output_r_BitWidth(XWritebinary *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XWRITEBINARY_S_AXI_BUNDLE_WIDTH_OUTPUT_R;
}

u32 XWritebinary_Get_output_r_Depth(XWritebinary *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XWRITEBINARY_S_AXI_BUNDLE_DEPTH_OUTPUT_R;
}

u32 XWritebinary_Write_output_r_Words(XWritebinary *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_HIGH - XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XWritebinary_Read_output_r_Words(XWritebinary *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_HIGH - XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_BASE + (offset + i)*4);
    }
    return length;
}

u32 XWritebinary_Write_output_r_Bytes(XWritebinary *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_HIGH - XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XWritebinary_Read_output_r_Bytes(XWritebinary *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_HIGH - XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XWRITEBINARY_S_AXI_BUNDLE_ADDR_OUTPUT_R_BASE + offset + i);
    }
    return length;
}

void XWritebinary_InterruptGlobalEnable(XWritebinary *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XWritebinary_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_GIE, 1);
}

void XWritebinary_InterruptGlobalDisable(XWritebinary *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XWritebinary_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_GIE, 0);
}

void XWritebinary_InterruptEnable(XWritebinary *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_IER);
    XWritebinary_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_IER, Register | Mask);
}

void XWritebinary_InterruptDisable(XWritebinary *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_IER);
    XWritebinary_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_IER, Register & (~Mask));
}

void XWritebinary_InterruptClear(XWritebinary *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XWritebinary_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_ISR, Mask);
}

u32 XWritebinary_InterruptGetEnabled(XWritebinary *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_IER);
}

u32 XWritebinary_InterruptGetStatus(XWritebinary *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XWritebinary_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XWRITEBINARY_S_AXI_BUNDLE_ADDR_ISR);
}

