// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xwritebinary.h"

extern XWritebinary_Config XWritebinary_ConfigTable[];

XWritebinary_Config *XWritebinary_LookupConfig(u16 DeviceId) {
	XWritebinary_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XWRITEBINARY_NUM_INSTANCES; Index++) {
		if (XWritebinary_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XWritebinary_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XWritebinary_Initialize(XWritebinary *InstancePtr, u16 DeviceId) {
	XWritebinary_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XWritebinary_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XWritebinary_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

